<a href="https://colab.research.google.com/github/Bazgha19/Tensor/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook, we're going to learn some of the most fundamental concpets of Tensors using TensorFLow



*  Introduction to tensors 
*  Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function(a way to speed up your regular Python function)
* Using GPUs with TensorFlow(or TPUs)
* Some Excercises



**Introduction to Tensors**

In [ ]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of our vector
vector.ndim

1

In [ ]:
#Create a matrix (has more than 1 dimension)
matrix = tf.constant([[18,19],[19,18]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 19],
       [19, 18]], dtype=int32)>

In [ ]:
#Check the dimension of matrix
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[18.,19.],[19.,18.],[12.,18.]], dtype=tf.float16) #specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[18., 19.],
       [19., 18.],
       [12., 18.]], dtype=float16)>

In [ ]:
#Check the dimension of another_matrix
another_matrix.ndim

2

In [ ]:
#Let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
#Check the dimension of this tensor
tensor.ndim

3

What I have created so far?
* Scalar: A single number
* Vector: A number with direction (e.g., wind speed and direction)
* Matrix: A 2-dimensional array of numbers
* Tensor: An n-dimensional array of numbers (where n can be any number, 0-dimensional tensor is a scalar, 1-dimensional tensor is a vector)