<a href="https://colab.research.google.com/github/Bazgha19/Tensor/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook, we're going to learn some of the most fundamental concpets of Tensors using TensorFLow



*  Introduction to tensors 
*  Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function(a way to speed up your regular Python function)
* Using GPUs with TensorFlow(or TPUs)
* Some Excercises



**Introduction to Tensors**

In [ ]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of our vector
vector.ndim

1

In [ ]:
#Create a matrix (has more than 1 dimension)
matrix = tf.constant([[18,19],[19,18]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 19],
       [19, 18]], dtype=int32)>

In [ ]:
#Check the dimension of matrix
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[18.,19.],[19.,18.],[12.,18.]], dtype=tf.float16) #specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[18., 19.],
       [19., 18.],
       [12., 18.]], dtype=float16)>

In [ ]:
#Check the dimension of another_matrix
another_matrix.ndim

2

In [ ]:
#Let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
#Check the dimension of this tensor
tensor.ndim

3

What I have created so far?
* Scalar: A single number
* Vector: A number with direction (e.g., wind speed and direction)
* Matrix: A 2-dimensional array of numbers
* Tensor: An n-dimensional array of numbers (where n can be any number, 0-dimensional tensor is a scalar, 1-dimensional tensor is a vector)

###Creating tensors with `tf.Variable`

In [31]:
#Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([18,19])
unchangeable_tensor = tf.constant([18,19])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([18, 19], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([18, 19], dtype=int32)>)

In [33]:
#Let's change one of the element in the changeable tensor
changeable_tensor[0] = 12
changeable_tensor

TypeError: ignored

In [36]:
#Try .assign() to change the element
changeable_tensor[0].assign(12)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12, 19], dtype=int32)>

In [38]:
#Let's change one element in the unchangeable tensor
unchangeable_tensor[0].assign(12)
unchangeable_tensor

AttributeError: ignored

🔑**Note:** Rarely in practice will you need to decide whether to use `tf.constant` or `tf.variable` to create tensors, as Tensorflow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

###Creating random Tensors
Random tensors are tensors of some arbitrary size which containe random numbers.

In [47]:
#Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

 ### Shuffle the order of elements in a tensor

In [52]:
 # Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
 not_shuffled = tf.constant([[18,19],
                             [19,18],
                             [12,18]])
# Shuffle our non-shuffeled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12, 18],
       [19, 18],
       [18, 19]], dtype=int32)>

In [64]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[18, 19],
       [19, 18],
       [12, 18]], dtype=int32)>

In [53]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[18, 19],
       [19, 18],
       [12, 18]], dtype=int32)>

⚒️**Excercise:** Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle.

In [73]:
# 5 random tensors and shuffle
shuffled1 = tf.constant([[12,19],
                         [18,19],
                         [19,18]])
s1 = tf.random.shuffle(shuffled1)

shuffled2 = tf.constant([[1,2],
                         [3,4],
                         [4,5]])
s2 = tf.random.shuffle(shuffled2)

shuffled3 = tf.constant([[10,9],
                         [9,8],
                         [8,7]])
s3 = tf.random.shuffle(shuffled3)

shuffled4 = tf.constant([[2,3],
                         [4,5],
                         [6,7]])
s4 = tf.random.shuffle(shuffled4)

shuffled5 = tf.constant([[12,2],
                         [18,12],
                         [19,5]])
s5 = tf.random.shuffle(shuffled5)
s1, s2, s3, s4, s5

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[12, 19],
        [19, 18],
        [18, 19]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 5],
        [3, 4]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 9,  8],
        [10,  9],
        [ 8,  7]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [6, 7],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[18, 12],
        [19,  5],
        [12,  2]], dtype=int32)>)